"""empty message

Revision ID: c18de593d107
Revises: 
Create Date: 2021-09-21 19:08:07.139313

"""
from alembic import op
import sqlalchemy as sa
import app.helper


# revision identifiers, used by Alembic.
revision = 'c18de593d107'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id_', app.helper.sqlalchemy.ObjectIDField(length=32), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=1024), nullable=False),
    sa.Column('username', sa.String(length=1024), nullable=True),
    sa.Column('password', sa.String(length=1024), nullable=False),
    sa.Column('name', sa.String(length=2048), nullable=False),
    sa.Column('gender', sa.Integer(), nullable=False),
    sa.Column('birthdate', sa.String(length=64), nullable=True),
    sa.Column('contact', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('section', sa.String(length=128), nullable=True),
    sa.Column('position', sa.String(length=128), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('activity', sa.String(length=128), nullable=True),
    sa.Column('extra_info', app.helper.sqlalchemy.DictField(), nullable=True),
    sa.Column('role', app.helper.sqlalchemy.DictField(), nullable=True),
    sa.Column('config', app.helper.sqlalchemy.DictField(), nullable=True),
    sa.Column('security_question', app.helper.sqlalchemy.DictField(), nullable=True),
    sa.Column('banned_expire', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_index(op.f('ix_user_deleted'), 'user', ['deleted'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_id_'), 'user', ['id_'], unique=False)
    op.create_table('user_password',
    sa.Column('id_', app.helper.sqlalchemy.ObjectIDField(length=32), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.Column('user_id', app.helper.sqlalchemy.ObjectIDField(length=32), nullable=False),
    sa.Column('password_prev', sa.String(length=512), nullable=False),
    sa.Column('password_new', sa.String(length=512), nullable=False),
    sa.Column('client_info', app.helper.sqlalchemy.DictField(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id_'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_index(op.f('ix_user_password_deleted'), 'user_password', ['deleted'], unique=False)
    op.create_index(op.f('ix_user_password_id_'), 'user_password', ['id_'], unique=False)
    op.create_table('user_token',
    sa.Column('id_', app.helper.sqlalchemy.ObjectIDField(length=32), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.Column('user_id', app.helper.sqlalchemy.ObjectIDField(length=32), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=True),
    sa.Column('secret', sa.String(length=512), nullable=True),
    sa.Column('expires', sa.DateTime(), nullable=True),
    sa.Column('client_info', app.helper.sqlalchemy.DictField(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id_'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_index(op.f('ix_user_token_deleted'), 'user_token', ['deleted'], unique=False)
    op.create_index(op.f('ix_user_token_id_'), 'user_token', ['id_'], unique=False)
    op.create_index(op.f('ix_user_token_token'), 'user_token', ['token'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_token_token'), table_name='user_token')
    op.drop_index(op.f('ix_user_token_id_'), table_name='user_token')
    op.drop_index(op.f('ix_user_token_deleted'), table_name='user_token')
    op.drop_table('user_token')
    op.drop_index(op.f('ix_user_password_id_'), table_name='user_password')
    op.drop_index(op.f('ix_user_password_deleted'), table_name='user_password')
    op.drop_table('user_password')
    op.drop_index(op.f('ix_user_id_'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_deleted'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
