"""empty message

Revision ID: e3496be33905
Revises: 
Create Date: 2021-09-29 15:12:36.823648

"""
from alembic import op
import sqlalchemy as sa
import app.helper
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e3496be33905'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate',
    sa.Column('id_', app.helper.sqlalchemy.ObjectIDField(length=32), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(length=128), nullable=False),
    sa.Column('leader_name', sa.Text(), nullable=False),
    sa.Column('deputy_name', sa.Text(), nullable=True),
    sa.Column('photo', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('campaign_video', sa.Text(), nullable=True),
    sa.Column('campaign_info', sa.Text(), nullable=True),
    sa.Column('extra_info', app.helper.sqlalchemy.DictField(), nullable=True),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_index(op.f('ix_candidate_deleted'), 'candidate', ['deleted'], unique=False)
    op.create_index(op.f('ix_candidate_id_'), 'candidate', ['id_'], unique=False)
    op.create_table('setting',
    sa.Column('id_', app.helper.sqlalchemy.ObjectIDField(length=32), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.Column('identifier', sa.String(length=16), nullable=False),
    sa.Column('vote_start', sa.DateTime(), nullable=True),
    sa.Column('vote_end', sa.DateTime(), nullable=True),
    sa.Column('template', mysql.LONGTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_index(op.f('ix_setting_deleted'), 'setting', ['deleted'], unique=False)
    op.create_index(op.f('ix_setting_id_'), 'setting', ['id_'], unique=False)
    op.create_table('user',
    sa.Column('id_', app.helper.sqlalchemy.ObjectIDField(length=32), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=1024), nullable=False),
    sa.Column('username', sa.String(length=1024), nullable=True),
    sa.Column('password', sa.String(length=1024), nullable=False),
    sa.Column('name', sa.String(length=2048), nullable=False),
    sa.Column('gender', sa.Integer(), nullable=False),
    sa.Column('birthdate', sa.String(length=64), nullable=True),
    sa.Column('contact', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('section', sa.String(length=128), nullable=True),
    sa.Column('position', sa.String(length=128), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('activity', sa.String(length=128), nullable=True),
    sa.Column('extra_info', app.helper.sqlalchemy.DictField(), nullable=True),
    sa.Column('role', app.helper.sqlalchemy.DictField(), nullable=True),
    sa.Column('config', app.helper.sqlalchemy.DictField(), nullable=True),
    sa.Column('security_question', app.helper.sqlalchemy.DictField(), nullable=True),
    sa.Column('banned_expire', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_index(op.f('ix_user_deleted'), 'user', ['deleted'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_id_'), 'user', ['id_'], unique=False)
    op.create_table('voter',
    sa.Column('id_', app.helper.sqlalchemy.ObjectIDField(length=32), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.Column('id_number', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('pin', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('birthdate', sa.String(length=64), nullable=True),
    sa.Column('contact', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('confirm_at', sa.DateTime(), nullable=True),
    sa.Column('confirm_by', app.helper.sqlalchemy.ObjectIDField(length=32), nullable=True),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('extra_info', app.helper.sqlalchemy.DictField(), nullable=True),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_index(op.f('ix_voter_deleted'), 'voter', ['deleted'], unique=False)
    op.create_index(op.f('ix_voter_id_'), 'voter', ['id_'], unique=False)
    op.create_table('user_password',
    sa.Column('id_', app.helper.sqlalchemy.ObjectIDField(length=32), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.Column('user_id', app.helper.sqlalchemy.ObjectIDField(length=32), nullable=False),
    sa.Column('password_prev', sa.String(length=512), nullable=False),
    sa.Column('password_new', sa.String(length=512), nullable=False),
    sa.Column('client_info', app.helper.sqlalchemy.DictField(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id_'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_index(op.f('ix_user_password_deleted'), 'user_password', ['deleted'], unique=False)
    op.create_index(op.f('ix_user_password_id_'), 'user_password', ['id_'], unique=False)
    op.create_table('user_token',
    sa.Column('id_', app.helper.sqlalchemy.ObjectIDField(length=32), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.Column('user_id', app.helper.sqlalchemy.ObjectIDField(length=32), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=True),
    sa.Column('secret', sa.String(length=512), nullable=True),
    sa.Column('expires', sa.DateTime(), nullable=True),
    sa.Column('client_info', app.helper.sqlalchemy.DictField(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id_'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_index(op.f('ix_user_token_deleted'), 'user_token', ['deleted'], unique=False)
    op.create_index(op.f('ix_user_token_id_'), 'user_token', ['id_'], unique=False)
    op.create_index(op.f('ix_user_token_token'), 'user_token', ['token'], unique=False)
    op.create_table('voter_ballot',
    sa.Column('id_', app.helper.sqlalchemy.ObjectIDField(length=32), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.Column('candidate_id', app.helper.sqlalchemy.ObjectIDField(length=32), nullable=False),
    sa.Column('voter_id', app.helper.sqlalchemy.ObjectIDField(length=32), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id_'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voter_id'], ['voter.id_'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_index(op.f('ix_voter_ballot_deleted'), 'voter_ballot', ['deleted'], unique=False)
    op.create_index(op.f('ix_voter_ballot_id_'), 'voter_ballot', ['id_'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voter_ballot_id_'), table_name='voter_ballot')
    op.drop_index(op.f('ix_voter_ballot_deleted'), table_name='voter_ballot')
    op.drop_table('voter_ballot')
    op.drop_index(op.f('ix_user_token_token'), table_name='user_token')
    op.drop_index(op.f('ix_user_token_id_'), table_name='user_token')
    op.drop_index(op.f('ix_user_token_deleted'), table_name='user_token')
    op.drop_table('user_token')
    op.drop_index(op.f('ix_user_password_id_'), table_name='user_password')
    op.drop_index(op.f('ix_user_password_deleted'), table_name='user_password')
    op.drop_table('user_password')
    op.drop_index(op.f('ix_voter_id_'), table_name='voter')
    op.drop_index(op.f('ix_voter_deleted'), table_name='voter')
    op.drop_table('voter')
    op.drop_index(op.f('ix_user_id_'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_deleted'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_setting_id_'), table_name='setting')
    op.drop_index(op.f('ix_setting_deleted'), table_name='setting')
    op.drop_table('setting')
    op.drop_index(op.f('ix_candidate_id_'), table_name='candidate')
    op.drop_index(op.f('ix_candidate_deleted'), table_name='candidate')
    op.drop_table('candidate')
    # ### end Alembic commands ###
